### ISSUE TITLE
What is the recommended version of R? 

### ISSUE THREAD

**Issue by dorkylever** [ZYBunnyHu/masonmd#1]
Hi Everyone, 

What is the R-version required for MASONMD? 

Kind Regards,
Kyle Drover

**Comment by zhiyhu** [comment]
Hi Kyle,

This package was designed in R 3.3

Best,
Zhiyuan

**Comment by zhiyhu** [comment]
Hi Kyle,

I will close this issue in one week if that is okay for you.

BW
Zhiyuan
